import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { PNG } from 'pngjs';

// src/lib/__tests__ → ../../../ = apps/mobile
const ASSET = join(dirname(fileURLToPath(import.meta.url)), '../../../assets/splash-icon.png');

describe('splash-icon.png (generated by scripts/build-splash.mjs)', () => {
  it('exists', () => {
    expect(existsSync(ASSET)).toBe(true);
  });

  it('is a valid PNG with positive dimensions', () => {
    const png = PNG.sync.read(readFileSync(ASSET));
    expect(png.width).toBeGreaterThan(0);
    expect(png.height).toBeGreaterThan(0);
  });

  it('has a transparent background (top-left pixel alpha === 0)', () => {
    const png = PNG.sync.read(readFileSync(ASSET));
    // pixel (0,0) alpha is the 4th byte; artwork is centered on transparency
    expect(png.data[3]).toBe(0);
  });
});
